### ISSUE TITLE
Create Drive subsystem

### ISSUE THREAD

**Issue by cpdupuis** [KentridgeRobotics/2017Robot-Controls#2]
This is the code that actually drives the wheel motors.

**Comment by cpdupuis** [comment]
Use the 2016 project as an example:
https://github.com/KentridgeRobotics/2016Robot/blob/master/2016%20Competition%20Robot/src/org/usfirst/frc/team3786/robot/subsystems/DriveTrain.java

**Comment by AaronWebermaster** [comment]
Drive system is made, will fine tune how the speed part works once we have an actual robot to work with
